### ISSUE TITLE
Does anyone tried svelthree with sapper?

### ISSUE THREAD

**Issue by llPekoll** [vatro/svelthree#31]
Hi,
I am trying to run svelthree with sapper,
I've installed typescript
then I tried to make it 'SSR', but I can't find some files like "svelthree/src/components/BoxBufferGeometry.svelte",
finally, when I commented on the missing part, run into an 
500 error
Cannot read property 'scenes' of undefined
```
<script>
    import Canvas from "svelthree/src/components/Canvas.svelte";
    import Scene from "svelthree/src/components/Scene.svelte";
    import PerspectiveCamera from "svelthree/src/components/PerspectiveCamera.svelte";
    import DirectionalLight from "svelthree/src/components/DirectionalLight.svelte";
    import AmbientLight from "svelthree/src/components/AmbientLight.svelte";
    // import BoxBufferGeometry from "svelthree/src/components/BoxBufferGeometry.svelte";
    import Mesh from "svelthree/src/components/Mesh.svelte";
    // import MeshStandardMaterial from "svelthree/src/components/MeshStandardMaterial.svelte";
    import WebGLRenderer from "svelthree/src/components/WebGLRenderer.svelte";
  // or from "https://unpkg.com/svelthree@latest/dist/svelthree.mjs" in REPL

  // let cubeGeometry = new BoxBufferGeometry(1, 1, 1);
  // let cubeMaterial = new MeshStandardMaterial();
</script>

<Canvas let:sti w={500} h={500}>

  <Scene {sti} let:scene id="scene1" props={{ background: 0xedf2f7 }}>

    <PerspectiveCamera {scene} id="cam1" pos={[0, 0, 3]} lookAt={[0, 0, 0]} />
    <AmbientLight {scene} intensity={1.25} />
    <DirectionalLight {scene} pos={[3, 3, 3]} />

    <!-- <Mesh
      {scene}
      geometry={cubeGeometry}
      material={cubeMaterial}
      mat={{ roughness: 0.5, metalness: 0.5, color: 0xff3e00 }}
      pos={[0, 0, 0]}
      rot={[0.5, 0.6, 0]}
      scale={[1, 1, 1]} /> -->

  </Scene>

  <WebGLRenderer
    {sti}
    sceneId="scene1"
    camId="cam1"
    config={{ antialias: true, alpha: false }} />

</Canvas>
```
Any plan to make it sapper compatible?

**Comment by vatro** [comment]
Hi!

**there is no BoxBufferGeometry.svelte component**!
You should import BoxBufferGeometry from the package as you would from "three" (not as a Svelte component), the same is with all other Geometries and Materials. Install the npm package and **import from "svelthree"**.

**Sapper compatibility should be given**, but I haven't tried all scenarios yet. Please try again when you're properly importing Geometries and Materials.

See e.g. [Hello cube](https://svelthree.dev/repl/hello-cube?version=3.29.0).
Also **see** [CHANGELOG.md](https://github.com/vatro/svelthree/blob/dev/CHANGELOG.md) **for the list of available components**.

More Docs / API coming soon, thank you for trying out svelthree! 👍

**Comment by vatro** [comment]
Closing, please open a new issue if there's still a problem after importing Geometries and Materials correctly. Thanks.
