### ISSUE TITLE
How do I add edges and lines to a scene?

### ISSUE THREAD

**Issue by GitNoise** [vatro/svelthree#34]
I am trying to add edges to a an object using Svelthree.

I know how to add a geometry to a scene using mesh but how do I add lines at the edges of the geometry?

This is from the official REPL (https://svelthree.dev/examples#hello-cube):

```
 <Scene {sti} let:scene id="scene1" props={{ background: 0xedf2f7 }}>

<PerspectiveCamera {scene} id="cam1" pos={[0, 0, 3]} lookAt={[0, 0, 0]} />
<AmbientLight {scene} intensity={1.25} />
<DirectionalLight {scene} pos={[3, 3, 3]} />

<Mesh
  {scene}
  geometry={cubeGeometry}
  material={cubeMaterial}
  mat={{ roughness: 0.5, metalness: 0.5, color: 0xff3e00 }}
  pos={[0, 0, 0]}
  rot={[0.5, 0.6, 0]}
  scale={[1, 1, 1]} />
```

https://stackoverflow.com/questions/64948143/svelthree-how-do-i-add-edges-and-lines-to-a-scene

**Comment by vatro** [comment]
Hi! 🙂

There is no 'Line'-Component "at the moment" (maybe there will be one in future, don't know yet), but you can use **vanilla three** to **add a Line** either **to the mesh instance** itself or **to the scene instance** itself!

- **get** the **Mesh instance**: `bind:this={myMesh}` on the component and then e.g. `let mesh = myMesh.getMesh()`
- **get** the **Scene instance**:  `bind:this={myScene}` on the component and then e.g. `let scene = myScene.getScene()`

With Mesh and Scene instances available, you can basically do anything you want vanilla three style.

See REPL (based on 'Hello cube'): https://svelthree.dev/repl/b487071cb04f4065bd62de9a6f5b838a?version=3.30.0

Thank you for trying svelthree! 😎 Stay tuned! ✌️
