### ISSUE TITLE
How do I disable the console messages?

### ISSUE THREAD

**Issue by braebo** [vatro/svelthree#36]
Thanks for Svelthree!

I was wondering how I might disable the console messages from Svelthree.  It's rather noisy 😅

**Comment by vatro** [comment]
true! 😅 that's due to my early development needs.

The easiest way would be to either completely disable **info** level logs (as those are the noisy ones) or purge them via e.g. a [**terser**-plugin](https://github.com/TrySound/rollup-plugin-terser).

**Comment by vatro** [comment]
Closing this. I'm aware that the logging is being somewhat non-optimal atm, will think about a better solution in future (like setting --verbose true / false in dev mode or similar). Suggestions and advice are always welcome!

**Comment by mate-h** [comment]
![Screenshot 2022-07-28 at 12 17 17](https://user-images.githubusercontent.com/14351670/181608966-d5f8b4e1-e59d-4b82-99ca-eb5d3e8815bd.png)
Using negated console filter `-SVELTHREE` seems to do the job!

**Comment by vatro** [comment]
> ![Screenshot 2022-07-28 at 12 17 17](https://user-images.githubusercontent.com/14351670/181608966-d5f8b4e1-e59d-4b82-99ca-eb5d3e8815bd.png)
> 
> Using negated console filter `-SVELTHREE` seems to do the job!

cool, wasn't aware of this possibility! Newer versions have completely different  handling of logs (using `-verbose` arg), but this is still a TODO, needs to be made the correct way, conditional logs should be completely stripped from output if compiled without `-verbose`.
