### ISSUE TITLE
Reactively resizing canvas

### ISSUE THREAD

**Issue by Somfic** [vatro/svelthree#38]
Heya, thanks for the amazing library!

I'd like to reactively resize the canvas to the width and height of a DOM component. 

This is what I have so far:
```svelte
<script lang="ts">
    import {
        Canvas,
        Scene,
        PerspectiveCamera,
        DirectionalLight,
        IcosahedronGeometry,
        WireframeGeometry,
        Mesh,
        MeshStandardMaterial,
        WebGLRenderer,
        OrbitControls
    } from "svelthree";

    let planetGeo = new IcosahedronGeometry(1, 2);
    let planetMat = new MeshStandardMaterial();
    planetMat.wireframe = true;

    let width;
    let height;
</script>

<main bind:clientWidth={width} bind:clientHeight={height}>
    <Canvas let:sti w={width} h={height} id="canvas">

        <Scene {sti} let:scene id="scene1" props={{ background: 0x000 }}>

            <PerspectiveCamera {scene} id="cam1" pos={[0, 0, 3]} lookAt={[0, 0, 0]}/>
            <DirectionalLight {scene} pos={[3, 3, 3]}/>

            <Mesh
                    {scene}
                    geometry={planetGeo}
                    material={planetMat}
                    mat={{ roughness: 0.5, metalness: 0.5, color: 0xfff }}
                    pos={[0, 0, 0]}
                    rot={[0, 0, 0]}
                    scale={[1, 1, 1]}/>

            <OrbitControls {scene} enableDamping/>

        </Scene>

        <WebGLRenderer
                {sti}
                sceneId="scene1"
                camId="cam1"
                config={{ antialias: true, alpha: true }}/>

    </Canvas>
</main>

<style>
    main {
        height: 100%;
        width: 100%;
    }
</style>
```

The main DOM element resizes with the browser window, so should the canvas. However, this is the result I get:
![image](https://user-images.githubusercontent.com/29230467/115601496-2dd05700-a2de-11eb-81f6-f48397198cf3.png)

After some debugging, I figured it grabs the initial value of the `width` and `height` variables to set up the canvas. If I set `width` and `height` both to 500 on initialization, for example, this is my result:
![image](https://user-images.githubusercontent.com/29230467/115601818-83a4ff00-a2de-11eb-91a8-c5a0481a3eb1.png)

Resizing the browser window has no effect. The `height` and `width` variables *are* however reactively being updated by Svelte, but it seems there's no effect on the canvas/renderer width and size.

Is there something I am missing here? 

Thank you!

**Comment by vatro** [comment]
Hi, sorry for the late response. Yeah, this is a bit cumbersome in the current (the only) release, **you have to resize the Canvas component manually** via [.doResize( w, h ) method](https://github.com/vatro/svelthree/blob/0d3e904117d9d83b36b6783fa8a3bc4d8cda6430/src/components/Canvas.svelte#L251-L253), please try one of these solutions (tested):

```svelte
<!-- reactive statement + 'doResize' -->
<script>
...

  let cnvs: Canvas

  $: width || height ? changeCanvasSize() : null

  function changeCanvasSize() {
	cnvs.doResize(width, height)
  }
</script>

<main bind:clientWidth={width} bind:clientHeight={height}>
  <Canvas let:sti w={width} h={height} bind:this={cnvs}>
   ...
  </Canvas>
</main>

```
or

```svelte
<!-- window: resize event + 'doResize' -->
<script>
...

  import {onMount} from "svelte"

  let cnvs: Canvas

  onMount(() => {
	window.addEventListener("resize", onResize);
	onResize(null)
  })

  function onResize(e): void {
	cnvs.doResize(width, height)
  }
</script>

<main bind:clientWidth={width} bind:clientHeight={height}>
  <Canvas let:sti w={width} h={height} bind:this={cnvs}>
   ...
  </Canvas>
</main>
```

Hope this helps + thanks for trying out svelthree! 👍
Stay tuned and pump up the jam! 😎
