### ISSUE TITLE
Antialiasing does not seem to work.

### ISSUE THREAD

**Issue by gschian0** [vatro/svelthree#40]
CustomShaderCube.svelte file
`<script>
  import { onMount } from "svelte";
  import {
    Canvas,
    Scene,
    PerspectiveCamera,
    DirectionalLight,
    //BasicShadowMap,
    //PCFShadowMap,
    PCFSoftShadowMap,
    //VSMShadowMap,
    AmbientLight,
    BoxBufferGeometry,
    PlaneBufferGeometry,
    Mesh,
    MeshStandardMaterial,
    WebGLRenderer,
    OrbitControls,
    DoubleSide,
    MathUtils,
		ShaderMaterial,
  } from "svelthree";

  let cubeGeometry = new BoxBufferGeometry(1, 1, 1);
  let cubeMaterial = new ShaderMaterial({uniforms: { time : {value : 0}}});
  let cube;
  let cubeMesh;
  let floorGeometry = new PlaneBufferGeometry(4, 4, 1);
  let floorMaterial = new MeshStandardMaterial();

  onMount(() => {
    cubeMesh = cube.getMesh();
    rotateCube();

    return () => {
      console.log("MyRotatingCube > onDestroy!");
      onDestroy();
    };
  });

  let rAF = 0;
  let doRotate = false;

  function rotateCube() {
    startRotating();
  }

  function startRotating() {
    doRotate = true;
    rAF = requestAnimationFrame(rotate);
  }

  function rotate() {
    if (doRotate) {
      cubeMesh.rotation.x += 0.01;
      cubeMaterial.uniforms.time.value += 0.01;
      cubeMesh.rotation.y += 0.01;
      cubeMesh.rotation.z += 0.01;
      rAF = requestAnimationFrame(rotate);
    }
  }

  function onDestroy() {
    console.log("MyRotatingCube > 'onDestroy' cleanup function triggered!");
    doRotate = false;
    cancelAnimationFrame(rAF);
  }

	
	let frag = `
uniform float time;
uniform float progress;
uniform sampler2D texture1;
uniform vec4 resolution;
varying vec2 vUv;
varying vec3 vPosition;
uniform vec3 color;
float PI = 3.141592653589793238;
void main()	{
	// vec2 newUV = (vUv - vec2(0.5))*resolution.zw + vec2(0.5);
	gl_FragColor = vec4(vec3(vUv.x, vUv.y, sin(vUv.x+time)),1.);
}
	`
	
	let vert = `
	uniform float time;
varying vec2 vUv;
varying vec3 vPosition;
uniform vec2 pixels;
float PI = 3.141592653589793238;
void main() {
  vUv = uv;
  gl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );
}
	`
</script>

<Canvas let:sti w={window.innerWidth} h={window.innerHeight}>

  <Scene {sti} let:scene id="scene1" props={{ background: 0xedf2f7 }}>

    <PerspectiveCamera {scene} id="cam1" pos={[0, 0, 3]} lookAt={[0, 0, 0]} />
    <AmbientLight {scene} intensity={1.25} />
    <DirectionalLight
      {scene}
      pos={[1, 2, 1]}
      intensity={0.8}
      shadowMapSize={512 * 8}
      castShadow />

    <Mesh
      {scene}
      bind:this={cube}
      geometry={cubeGeometry}
      
      material={cubeMaterial}
      mat={{ fragmentShader: frag, vertexShader:vert, uniforms:{time:{value: 0}} }}
      pos={[0, 0, 0]}
      rot={[0, 0, 0]}
      castShadow
      // receiveShadow />

    <Mesh
      {scene}
      geometry={floorGeometry}
      material={floorMaterial}
      mat={{ roughness: 0.5, metalness: 0.5, side: DoubleSide, color: 0xf7fafc }}
      pos={[0, -1, 0]}
      rot={[MathUtils.degToRad(-90), 0, 0]}
      scale={[1, 1, 1]}
      receiveShadow />

    <OrbitControls {scene}  enableDamping />

  </Scene>

  <WebGLRenderer
    {sti}
    sceneId="scene1"
    camId="cam1"
    config={{ antialias: true, alpha: false }}
    enableShadowMap
    shadowMapType={PCFSoftShadowMap} />

</Canvas>
`
App.svelte
`<script>
  import { onMount } from "svelte";
  import CustomShaderCube from "./CustomShaderCube.svelte";

	/**
	* The reference 'rotatingCube' is only for testing 'onDestroy' animation functionality (see 'onMount'), this is not the reference for rotation!
	* See 'MyRotatingCube.svelte' for rotation via reference ('cube').
	*/
  let customShaderCube;

  onMount(() => {
    // Test 'onDestroy' inside 'MyRotatingCube'
    // setTimeout(() => rotatingCube.$destroy(), 3000)
  });
</script>

<CustomShaderCube bind:this={customShaderCube} />`

main.ts
`import App from './App.svelte';

const app = new App({
	target: document.body,
	props: {
		name: 'world'
	}
});

export default app;`

I like the feel of this framework... would love to get it looking crisp!

<img width="1440" alt="Screen Shot 2021-05-10 at 3 03 13 PM" src="https://user-images.githubusercontent.com/54407820/117711163-e6344100-b1a0-11eb-8988-1b45866de724.png">

**Comment by gschian0** [comment]
also... why is the console so verbose ?

**Comment by vatro** [comment]
Could you please reformat your first question? ;) thanks!
Antialiasing works, antialiasing is essential. see e.g.: https://svelthree.dev/repl/hello-cube?version=3.38.2

Please make sure your Canvas resolution is high enough (px dimensions, not scaled), atm there's a caveat with resizing the Canvas component, see possible solution here: https://github.com/vatro/svelthree/issues/38#issuecomment-834744922

**Comment by vatro** [comment]
> also... why is the console so verbose ?

This is due to early development phase, atm you can e.g. strip `console.info` messages via terser when bundling, there'll be some more convenient method for this in the next release. Please keep in mind, svelthree is not production ready yet.
