### ISSUE TITLE
Antialias does not seem to be working.

### ISSUE THREAD

**Issue by gschian0** [vatro/svelthree#41]
Hey, got an example together using a custom shader material but antialias does not seem to be working... is it due to canvas size being set to small at some point of the app?  
here is a link to a sandbox where I feel the image is pretty grainy compared to what I get using three.js alone.  

https://codesandbox.io/s/custom-shadercube-svelte-fix1-j0lxn?file=/CustomShaderCube.svelte

**Comment by gschian0** [comment]
i need to access 

`renderer.setPixelRatio(window.devicePixelRatio);`

I'm trying this...

`<WebGLRenderer
    {sti}
    sceneId="scene1"
    camId="cam1"
    config={{ antialias: true, alpha: false }}
    enableShadowMap
    PixelRatio = {pixels}
    shadowMapType={PCFSoftShadowMap} />`

**Comment by vatro** [comment]
Hi,

`devicePixelRatio` cannot be set via the component interface (currently), but you can get the vanilla threejs renderer instance via `renderer_component_instance.getRenderer()` and do it, e.g.:

```html
<script>
import { onMount, tick } from "svelte";

let rend

onMount(async () => {
    await tick()
    rend.getRenderer().setPixelRatio(0.5)
  })

</script>
<WebGLRenderer bind:this={rend} ... />
```

but you can also do something like this for e.g. **HiDPI** resolutions (_**without** using **.setPixelRatio**_):

```html
<Canvas let:sti w={window.innerWidth*2} h={window.innerHeight*2} style="transform-origin: 0 0; scale:0.5">
```

hope this helps + either way, **antialiasing works**! ;)
Reminder for me: #22

**Comment by gschian0** [comment]
Can do that for now, thanks for walking me through the syntax.  I feel having the pixel ratio setting exposed is pretty important in my opinion or you can just do this when it’s created so people with retina displays don’t feel like the renderer is janky...

renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));

**Comment by vatro** [comment]
I will reconsider quite some things concerning WebGLRenderer component soon, see #22.

Btw. you should be careful with serving 2x resolutions, this can be a major performance bottleneck on mobile devices / HiDPI screens. E.g. just try to display something a bit more complicated / animated fullscreen on an "old" MacBook in 2x and see / hear it melting away with low framerates. ;)
