### ISSUE TITLE
GridHelper? How to add it?

### ISSUE THREAD

**Issue by j2l** [vatro/svelthree#44]
Hi @vatro !
Thank you very much for this great project!
I'd like to add the GridHelper, I understand that GridHelper.js is already there but it needs a long .svelte file to be able to add it in the scene, but nothing more :)

How would this svelte file is built?

**Comment by vatro** [comment]
Hi! Here's the modified 'Hello Cube' REPL example showing how to do it:
https://svelthree.dev/repl/0d5896d891014f95aed4ca2dc51849cc?version=3.42.1

Thanks for trying svelthree + stay tuned! 👍
